#%RAML 1.0 DataType

displayName: Address
type: object

properties:
  
  address1:
    displayName: Address 1
    description: The first address line for the carrier/supplier of the memo 
    type: string
    required: false
    example:
      "Test - Address - 01"

  address2:
    displayName: Address 2
    description: The second address line for the carrier/supplier of the memo
    type: string
    required: false
    example:
      "Test - Address - 02"
  
  address3:
    displayName: Address 3
    description: The third address line for the carrier/supplier of the memo
    type: string
    required: false
    example:
      "Test - Address - 03"
  
  city:
    displayName: City
    description: The city for the contact's address
    type: string
    required: false
    example:
      "Tampa"
  
  state:
    displayName: State
    description: The state for the contact's address
    type: string
    required: false
    example:
      "Florida"
  
  postalCode:
    displayName: Postal Code
    description: The postal code for the contact's address
    type: string
    required: false
    example:
      "33647"
  
  country:
    displayName: Country
    description: The country code for the contact's address
    type: string
    required: false
    example:
      "US"    