#%RAML 1.0 DataType

displayName: "Agency #"
description: A unique 8-digit numeric code that identifies an ARC participating agency
type: string
pattern: ^[0-9]+
minLength: 8
maxLength: 8
example:
  "11111111"