#%RAML 1.0 DataType
displayName: Adjust Balance
description: Adjust the memo balance
type:
enum: 
  [ 
    Change balance to,
    Decrease balance by,
    Increase balance by    
  ]  
example: 
  Change balance to
