#%RAML 1.0 DataType
displayName: Reason Catagory
description: Agency requested change to primary memo reason category
type:
enum: 
  [ 
    ARC MarketPlace,
    Booking,
    Chargeback,
    Commission,
    Exchange,
    Fare,
    Fee,
    Miscellaneous,
    Refund,
    Tax
  ]   
example: 
  Commission