#%RAML 1.0 DataType
displayName: Memo Reason 
description: Agency requested change to the airline-assigned reason for the memo being issued 
type:
enum: 
  [ 
    ACCOMPANIED TRAVEL CATEGORY 13 FARE RULE VIOLATION,
    ADVANCE RESERVATIONS AND TICKETING - CATEGORY 5 FARE RULE VIOLATION,
    AGENT DISCOUNTS - CATEGORY 21 FARE RULE VIOLATION,
    ALL OTHER DISCOUNTS - CATEGORY 22 FARE RULE VIOLATION,
    APPLICATION AND OTHER CONDITIONS - CATEGORY 50 FARE RULE VIOLATION,
    ARC MARKETPLACE,
    AUDIT RECOVERY FEE - MISCELLANEOUS,
    AUDIT RECOVERY FEE FOR EXCHANGE REPORTING ERRORS,
    AUDIT RECOVERY FEE FOR INCORRECT DATA,
    AUDIT RECOVERY FEE FOR LATE OR NO REPORTING ERRORS,
    AUDIT RECOVERY FEE FOR MISSING DATA,
    AUDIT RECOVERY FEE FOR REFUND REPORTING ERRORS,
    BLACKOUT DATES - CATEGORY 11 FARE RULE VIOLATION,
    CHILD/INFANT DISCOUNTS - CATEGORY 19 FARE RULE VIOLATION,
    CHURNING,
    COMBINABILITY - CATEGORY 10 FARE RULE VIOLATION,
    DAY/TIME APPLICATION - CATEGORY 2 FARE RULE VIOLATION,
    DEPOSITS - CATEGORY 29 FARE RULE VIOLATION,
    DOESN'T RECOGNIZE TRANSACTION,
    DUPLICATE BOOKINGS/RESERVATIONS,
    DUPLICATE PROCESSING,
    DUPLICATE PROCESSING,
    ELIGIBILITY - CATEGORY 1  FARE RULE VIOLATION,
    EX - ACCOMPANIED TRAVEL - CATEGORY 13 FARE RULE VIOLATION,
    EX - ADVANCE RESERVATIONS AND TICKETING CATEGORY 5 FARE RULE VIOLATION,
    EX - AGENT DISCOUNTS CATEGORY 21 FARE RULE VIOLATION,
    EX - ALL OTHER DISCOUNTS CATEGORY 22 FARE RULE VIOLATION,
    EX - APPLICATION AND OTHER CONDITIONS CATEGORY 50 FARE RULE VIOLATION,
    EX - BLACKOUT DATES - CATEGORY 11 FARE RULE VIOLATION,
    EX - CHILD/INFANT DISCOUNTS CATEGORY 19 FARE RULE VIOLATION,
    EX - COMBINABILITY CATEGORY 10 FARE RULE VIOLATION,
    EX - DAY/TIME APPLICATION CATEGORY 2 FARE RULE VIOLATION,
    EX - DEPOSITS CATEGORY 29 FARE RULE VIOLATION,
    EX - ELIGIBILITY CATEGORY 1  FARE RULE VIOLATION,
    EX - EXCHANGE NOT ALLOWED,
    EX - EXCHANGE VALIDITY ERROR,
    EX - FARE BY RULE CATEGORY 25 FARE RULE VIOLATION,
    EX - FARE RULES VIOLATIONS - MULTIPLE RULES,
    EX - FARE UNDER COLLECTED - DISCOUNT NOT ALLOWED,
    EX - FARE UNDER COLLECTED - INVALID TOUR OR TICKET DESIGNATOR,
    EX - FARE UNDER COLLECTED - MISSING TOUR OR TICKET DESIGNATOR,
    EX - FARE UNDER COLLECTED - OTHER,
    EX - FLIGHT APPLICATION CATEGORY 4 FARE RULE VIOLATION,
    EX - GROUP FARES CATEGORY 26 FARE RULE VIOLATION,
    EX - INCORRECT COMMISSIONS,
    EX - INCORRECT COMMISSIONS - INVALID TOUR OR TICKET DESIGNATOR,
    EX - INCORRECT COMMISSIONS - MISSING TOUR OR TICKET DESIGNATOR,
    EX - MAXIMUM STAY CATEGORY 7 FARE RULE VIOLATION,
    EX - MINIMUM STAY  CATEGORY 6  FARE RULE VIOLATION,
    EX - MISCELLANEOUS PROVISIONS CATEGORY 23 FARE RULE VIOLATION,
    EX - NEGOTIATED FARES CATEGORY 35 FARE RULE VIOLATION,
    EX - NON-COMMISSIONABLE,
    EX - NON-COMMISSIONABLE - INVALID TOUR OR TICKET DESIGNATOR,
    EX - NON-COMMISSIONABLE - MISSING TOUR OR TICKET DESIGNATOR,
    EX - PENALTIES CATEGORY 16 PENALTIES,
    EX - PENALTY FEE NOT ACCURATELY COLLECTED,
    EX - PENALTY FEE NOT COLLECTED,
    EX - RECALL COMMISSIONS,
    EX - SALES RESTRICTIONS - CATEGORY 15 FARE RULE VIOLATION,
    EX - SALES RESTRICTIONS CATEGORY 17 FARE RULE VIOLATION,
    EX - SEASONALITY CATEGORY 3 FARE RULE VIOLATION,
    EX - STOPOVERS CATEGORY 8 FARE RULE VIOLATION,
    EX - SURCHARGES - CATEGORY 12 FARE RULE VIOLATION,
    EX - TAX CALCULATION IS INVALID,
    EX - TAXES COLLECTED UNDER ONE/WRONG CODE,
    EX - TAXES NOT COLLECTED,
    EX - TICKET ENDORSEMENTS CATEGORY 18  FARE RULE VIOLATION,
    EX - TOUR CONDUCTOR DISCOUNTS CATEGORY 20 FARE RULE VIOLATION,
    EX - TOURS CATEGORY 27 FARE RULE VIOLATION,
    EX - TRANSFERS CATEGORY 9 FARE RULE VIOLATION,
    EX - TRAVEL RESTRICTIONS CATEGORY 14 FARE RULE VIOLATION,
    EX - VISIT ANOTHER COUNTRY CATEGORY 28  FARE RULE VIOLATION,
    EX - VOLUNTARY CHANGE ERROR CATEGORY 31  VOLUNTARY CHANGES,
    EX - VOLUNTARY EXCHANGE ERROR,
    EX - YQ/YR WAS NOT ACCURATELY COLLECTED,
    EX - YQ/YR WAS NOT COLLECTED,
    EXPIRED CARD,
    FARE BY RULE - CATEGORY 25 FARE RULE VIOLATION,
    FARE UNDER COLLECTED - DISCOUNT NOT ALLOWED,
    FARE UNDER COLLECTED - INVALID TOUR OR TICKET DESIGNATOR,
    FARE UNDER COLLECTED - MISSING TOUR OR TICKET DESIGNATOR,
    FARE UNDER COLLECTED - OTHER,
    FICTITIOUS NAMES,
    FLIGHT APPLICATION - CATEGORY 4 FARE RULE VIOLATION,
    GROUP DEPOSIT,
    GROUP FARES - CATEGORY 26 FARE RULE VIOLATION,
    GROUP/TOUR UTILIZATION,
    HIGHER INTERMEDIATE POINT - CATEGORY 17 FARE RULE VIOLATION,
    INACTIVE SEGMENTS,
    INCORRECT COMMISSIONS,
    INCORRECT COMMISSIONS - INVALID TOUR OR TICKET DESIGNATOR,
    INCORRECT COMMISSIONS - MISSING TOUR OR TICKET DESIGNATOR,
    INVALID CREDIT CARD NUMBER,
    INVALID REFUND CALCULATION - FARE ERROR,
    INVALID REFUND CALCULATION - TAX CALCULATION ERROR,
    INVALID/NO APPROVAL CODE,
    MARRIED SEGMENT VIOLATION,
    MAXIMUM STAY - CATEGORY 7 FARE RULE VIOLATION,
    MINIMUM STAY - CATEGORY 6 FARE RULE VIOLATION,
    MISCELLANEOUS PROVISIONS - CATEGORY 23 FARE RULE VIOLATION,
    MULTIPLE FARE RULE VIOLATIONS,
    MULTIPLE TAXES COLLECTED UNDER ONE/WRONG CODE,
    NAME CHANGE/CORRECTION ERROR,
    NEGOTIATED FARES - CATEGORY 35 FARE RULE VIOLATION,
    NON-COMMISSIONABLE,
    NON-COMMISSIONABLE - INVALID TOUR OR TICKET DESIGNATOR,
    NON-COMMISSIONABLE - MISSING TOUR OR TICKET DESIGNATOR,
    OTHER,
    OTHER BOOKING ERRORS,
    OTHER MISCELLANEOUS,
    PASSIVE SEGMENTS,
    RECALL COMMISSIONS,
    REFUND NOT RECEIVED,
    REFUND OF NON-REFUNDABLE FARE,
    REFUND PENALTY AMOUNT IS MISSING,
    REFUND PENALTY UNDER COLLECTED,
    REPORTING/SETTLEMENT ERRORS,
    SEASONALITY - CATEGORY 3 FARE RULE VIOLATION,
    SERVICE ISSUE,
    SPACE NOT CANCELLED,
    STOPOVERS - CATEGORY 8 FARE RULE VIOLATION,
    SURCHARGES - CATEGORY 12 FARE RULE VIOLATION,
    TAX CALCULATION IS INVALID,
    TAXES NOT COLLECTED,
    TICKET ENDORSEMENTS - CATEGORY 18  FARE RULE VIOLATION,
    TICKET VALIDITY ERROR,
    TOUR CONDUCTOR DISCOUNTS - CATEGORY 20 FARE RULE VIOLATION,
    TOURS - CATEGORY 27 FARE RULE VIOLATION,
    TRANSFERS - CATEGORY 9 FARE RULE VIOLATION,
    TRAVEL DATE RESTRICTIONS - CATEGORY 14 FARE RULE VIOLATION,
    UNAUTHORIZED/FRAUDULENT CHARGE,
    VARIOUS SALES RULE RESTRICTIONS - CATEGORY 15 FARE RULE VIOLATION,
    VISIT ANOTHER COUNTRY - CATEGORY 28 FARE RULE VIOLATION,
    VOLUNTARY REFUNDS - CATEGORY 33 FARE RULE VIOLATION,
    YQ/YR WAS NOT ACCURATELY CO
  ]   
example: 
  EX - TAX CALCULATION IS INVALID