#%RAML 1.0 DataType
displayName: Service Providers
description: Refers to the 4 digit SASI code
type: string
enum: 
  [ 
    "NONE",
    "0011",
    "0055",
    "0066",
    "0125",
    "0162",
    "0276",
    "0372",
    "0571",
    "2026",
    "4535",
    "5235",
    "5880",
    "6182",
    "7733",
    "7906",
    "8886",
    "8901",
    "9413",
    "9472",
    "9612",
    "9634",
    "9645",
    "9682"
  ]   
example: 
  "0011"