#%RAML 1.0 DataType
displayName: Primary Status
description: The primary status of a memo which includes Open, Closed and Inactive
type:
enum: 
  [ 
    All,
    Open,
    Closed,
    Inactive
  ]  
example: 
  Open
