#%RAML 1.0 DataType

displayName: TRS Reason
description: TRS Reason
type:
enum: 
  [
    Expired Card,
    Invalid Credit Card Number,
    Invalid/No Approval Code,
    Unauthorized Use,
    Fraudulent-Unauthorized Use,
    Flown and Refunded,
    Unreported Sale,
    Chgbk - All
  ]
example: 
  Invalid Credit Card Number
   