#%RAML 1.0 DataType

displayName: Resolution Type
description: One of the Revenue Recovery Services resolution products available to airlines
type:
enum: 
  [
    Carrier,
    TRS,
    MRS,
    TPRS
  ]
example: 
  Carrier
   