#%RAML 1.0 DataType
displayName: Secondary Status
description: Refers to the second or subordinate status of a memo
type:
enum: 
  [ 
    All,
    Aging Criteria Exceeded,
    Agent Action Required,
    Agent Ownership Change,
    By Carrier,
    Dispute Pending,
    New Memo,
    Payment Pending,
    Reactivated,
    Same as beginning,
    Paid Outside IAR,
    Settled in IAR,
    Sign Change Forced
  ]   
example: 
  Payment Pending