#%RAML 1.0 DataType

displayName: GDS Assignment Response
type: object
  
properties:  
  transactionMetadata:
    type: !include transaction-metadata.raml

  transactionResponse:
    displayName: Transaction Response
    description: Contains information about the response
    properties:
      message:
        required: false
        type: string
      memo:
        type: object
        required: false
        properties:
          validatingAirlineDesignator:
            type: !include validatingAirlineDesignator.raml
          agentNumericCode:
            type: !include agentNumericCode.raml
          memo:
            type: !include memo-number.raml
          field1:
            displayName: Flex Field 1
            description: One of six elements provided to the customer to use as needed in managing their work processes
            type: string
            required: false
            example:
              "Flex1"

          field2:
            displayName: Flex Field 2
            description: One of six elements provided to the customer to use as needed in managing their work processes
            type: string
            required: false
            example:
              "Flex2"

          field3:
            displayName: Flex Field 3
            description: One of six elements provided to the customer to use as needed in managing their work processes
            type: string
            required: false
            example:
              "Flex3"

          field4:
            displayName: Flex Field 4
            description: One of six elements provided to the customer to use as needed in managing their work processes
            type: string
            required: false
            example:
              "Flex4"

          field5:
            displayName: Flex Field 5
            description: One of six elements provided to the customer to use as needed in managing their work processes
            type: string
            required: false
            example:
              "Flex5"

          field6:
            displayName: Flex Field 6
            description: One of six elements provided to the customer to use as needed in managing their work processes
            type: string
            required: false
            example:
              "Flex6"

example: !include ../examples/memo-flex-fields-response.json   