#%RAML 1.0 DataType

displayName: Agency Reason  
type: object

properties:

  validatingAirlineDesignator:
    type: !include validatingAirlineDesignator.raml
    required: true
     
  agentNumericCode:
    type: !include agentNumericCode.raml
    required: true
  
  memo:
    type: !include memo-number.raml
    required: true

  agencyReason:
    description: Agencies can submit an Agency Reason.
    type: string
    required: true
    minLength: 1
    maxLength: 45
    example: Ticket was not auto-priced.
example: !include ../examples/memo-agency-reason-request.json    