#%RAML 1.0 DataType

displayName: Memo Change Reason
type: object

properties:
 
  categoryType:
    displayName: Category Type
    description: Agency requested change to primary memo reason category
    type: string
    example:
      "Booking"

  reasonType:
    displayName: Memo Reason Type
    description: Agency requested change to the airline-assigned reason for the memo being issued
    type: string
    example: 
      "CHURNING"     



  

