#%RAML 1.0 DataType

displayName: Memo Reason Response
type: object
  
properties:  
  transactionMetadata:
    type: !include transaction-metadata.raml

  transactionResponse:
    displayName: Transaction Response
    description: Contains information about the response
    properties:
      message:
        required: false
        type: string
      memo:
        type: object
        required: false
        properties:
          validatingAirlineDesignator:
            type: !include validatingAirlineDesignator.raml
          agentNumericCode:
            type: !include agentNumericCode.raml
          memo:
            type: !include memo-number.raml
          reasonCatagory:
            type: string
            example:
              value: "Booking"
          memoReason:
            type: string
            example: "DUPLICATE BOOKINGS/RESERVATIONS"
example: !include ../examples/memo-memo-reason-response.json    