#%RAML 1.0 DataType

displayName: Adjust Memo Balance response
type: object
  
properties:  
  transactionMetadata:
    type: !include transaction-metadata.raml

  transactionResponse:
    displayName: Transaction Response
    description: Contains information about the response
    properties:
      message:
        required: false
        type: string
      memo:
        type: object
        required: false
        properties:
          validatingAirlineDesignator:
            type: !include validatingAirlineDesignator.raml
          agentNumericCode:
            type: !include agentNumericCode.raml
          memo:
            type: !include memo-number.raml
          adjustBalance:
            type: string
            example:
              value: Increase balance by
          amount:
            type: string
            example: "175.00"
          correspondence:
            type: string
            example: This is a new adjust message Discover *1117 
example: !include ../examples/memo-balance-response.json    