#%RAML 1.0 DataType

displayName: "Carrier #"
description: A unique 3-digit numeric code that identifies the validating carrier
type: string
pattern: ^[0-9]+
minLength: 3
maxLength: 3
example: 
  "100"